# Generated by Django 6.0.2 on 2026-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('processor', models.CharField(blank=True, default='', max_length=200)),
                ('launched_year', models.IntegerField(blank=True, null=True)),
                ('user_rating', models.FloatField(default=0)),
                ('user_review', models.TextField(blank=True, default='')),
                ('camera_rating', models.FloatField(default=0)),
                ('battery_rating', models.FloatField(default=0)),
                ('design_rating', models.FloatField(default=0)),
                ('display_rating', models.FloatField(default=0)),
                ('performance_rating', models.FloatField(default=0)),
                ('memory_gb', models.IntegerField(default=0)),
                ('weight_g', models.FloatField(blank=True, null=True)),
                ('ram_gb', models.FloatField(default=0)),
                ('front_camera_mp', models.FloatField(default=0)),
                ('back_camera_mp', models.FloatField(default=0)),
                ('battery_mah', models.IntegerField(default=0)),
                ('price_inr', models.IntegerField(default=0)),
                ('screen_size', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'phones',
                'ordering': ['-user_rating'],
            },
        ),
    ]
